import { command, choose } from '../_helpers.js';
import { randomInt, getMentions, jidToMention } from '../../lib/utils.js';
import { createGuess, createAnswerGame, answerGuess, randomTrivia, startTictactoe, playTictactoe } from '../../lib/games.js';

export default [
  command({ name: 'tictactoe', aliases: ['ttt'], args: '<@usuario|casilla>', description: 'Inicia tres en raya o juega una casilla del 1 al 9.', category: 'game', execute: (ctx) => { const target = getMentions(ctx.message)[0]; const render = (board) => board.map((value, index) => value || String(index + 1)).reduce((rows, value, index) => { if (index % 3 === 0) rows.push([]); rows.at(-1).push(value); return rows; }, []).map((row) => row.join(' │ ')).join('\n─────────\n'); if (target) { if (target === ctx.sender) throw Object.assign(new Error('No puedes jugar contra ti mismo.'), { code: 'INVALID_OPTIONS' }); const result = startTictactoe(ctx.chat, ctx.sender, target); if (result.state === 'exists') return ctx.reply('♟️ Ya hay una partida activa en este chat.'); return ctx.reply(`♟️ Tres en raya iniciado. ${jidToMention(ctx.sender)} es X; ${jidToMention(target)} es O.\n\n${render(Array(9).fill(null))}\n\nTurno de X: usa ${ctx.prefix}tictactoe <1-9>.`, { mentions: [ctx.sender, target] }); } const result = playTictactoe(ctx.chat, ctx.sender, ctx.args[0]); if (result.state === 'missing') return ctx.reply(`No hay partida activa. Inicia con ${ctx.prefix}tictactoe @usuario.`); if (result.state === 'not-turn') return ctx.reply(`⏳ No es tu turno. Turno de ${jidToMention(result.turn)}.`, { mentions: [result.turn] }); if (result.state === 'invalid') return ctx.reply('❌ Casilla inválida u ocupada. Elige del 1 al 9.'); if (result.state === 'won') return ctx.reply(`🏆 Ganó ${jidToMention(result.winner)} (${result.mark}).\n\n${render(result.board)}`, { mentions: [result.winner] }); if (result.state === 'draw') return ctx.reply(`🤝 Empate.\n\n${render(result.board)}`); return ctx.reply(`${render(result.board)}\n\nTurno de ${jidToMention(result.turn)}.`, { mentions: [result.turn] }); } }),
  command({ name: 'trivia', args: '[respuesta]', description: 'Inicia o responde una trivia.', category: 'game', execute: (ctx) => { if (ctx.args.length) { const result = answerGuess(ctx.chat, ctx.sender, ctx.args.join(' '), 'trivia'); if (result.state === 'won') return ctx.reply('✅ ¡Correcto! Ganaste 20 XP.'); if (result.state === 'wrong') return ctx.reply('❌ Respuesta incorrecta.'); return ctx.reply('⌛ No hay una trivia activa para ti.'); } return ctx.reply(`🧠 Trivia: ${randomTrivia(ctx.chat, ctx.sender)}\nResponde con ${ctx.prefix}trivia <respuesta> en 2 minutos.`); } }),
  command({ name: 'mathgame', args: '[respuesta]', description: 'Juego matemático rápido.', category: 'game', execute: (ctx) => { if (ctx.args.length) { const result = answerGuess(ctx.chat, ctx.sender, ctx.args[0], 'math'); return ctx.reply(result.state === 'won' ? '✅ ¡Resultado correcto!' : result.state === 'wrong' ? '❌ No es correcto.' : '⌛ No hay partida activa.'); } const a = randomInt(2, 20); const b = randomInt(2, 20); createAnswerGame(ctx.chat, ctx.sender, a + b, 'math'); return ctx.reply(`➕ ¿Cuánto es ${a} + ${b}? Responde con ${ctx.prefix}mathgame <número> en 2 minutos.`); } }),
  command({ name: 'guess', args: '[numero]', description: 'Adivina un número entre 1 y 20.', category: 'game', execute: (ctx) => { if (ctx.args.length) { const result = answerGuess(ctx.chat, ctx.sender, ctx.args[0]); return ctx.reply(result.state === 'won' ? '🎉 ¡Adivinaste el número!' : result.state === 'wrong' ? '❌ No es ese número.' : '⌛ No hay juego activo.'); } createGuess(ctx.chat, ctx.sender); return ctx.reply(`🎯 Elegí un número entre 1 y 20. Responde con ${ctx.prefix}guess <número> en 2 minutos.`); } }),
  command({ name: 'coinflip', aliases: ['moneda'], description: 'Lanza una moneda.', category: 'game', execute: (ctx) => ctx.reply(`🪙 ${choose(['Cara', 'Cruz'])}`) }),
  command({ name: 'dice', aliases: ['dado'], description: 'Lanza un dado.', category: 'game', execute: (ctx) => ctx.reply(`🎲 Salió: *${randomInt(1, 6)}*`) }),
  command({ name: 'rps', aliases: ['piedrapapeltijera'], args: '<opcion>', description: 'Juega piedra, papel o tijera.', category: 'game', execute: (ctx) => { const valid = ['piedra', 'papel', 'tijera']; const pick = ctx.args[0]?.toLowerCase(); if (!valid.includes(pick)) throw Object.assign(new Error('Elige piedra, papel o tijera.'), { code: 'MISSING_ARGUMENT' }); const bot = choose(valid); const win = pick === bot ? 'Empate.' : (pick === 'piedra' && bot === 'tijera') || (pick === 'papel' && bot === 'piedra') || (pick === 'tijera' && bot === 'papel') ? '¡Ganaste!' : 'Perdiste.'; return ctx.reply(`Tú: ${pick}\nBot: ${bot}\n${win}`); } })
];
