import { command, requireText } from '../_helpers.js';

export default [
  command({ name: 'quran', description: 'Explica los comandos del Corán.', category: 'quran', execute: (ctx) => ctx.reply(`۞ Usa ${ctx.prefix}surah <número>, ${ctx.prefix}ayah <sura> <ayah>, ${ctx.prefix}quransearch <texto> o ${ctx.prefix}randomayah.`) }),
  command({ name: 'surah', args: '<numero>', description: 'Consulta una sura pública.', category: 'quran', limit: true, execute: async (ctx) => { const id = Number(ctx.args[0]); if (!Number.isInteger(id)) throw Object.assign(new Error('Debes escribir un número de sura.'), { code: 'MISSING_ARGUMENT' }); const data = await ctx.api.get('/api/v1/quran/surah', { id }); return ctx.reply(`۞ *${data.name}* (${data.englishName})\n${data.ayahs.slice(0, 10).map((a) => `${a.numberInSurah}. ${a.text}`).join('\n')}\n${data.ayahs.length > 10 ? '… (primeras 10 aleyas)' : ''}`); } }),
  command({ name: 'ayah', args: '<sura> <ayah>', description: 'Consulta una aleya.', category: 'quran', limit: true, execute: async (ctx) => { const [surah, ayah] = ctx.args.map(Number); if (!Number.isInteger(surah) || !Number.isInteger(ayah)) throw Object.assign(new Error('Debes indicar sura y aleya numéricas.'), { code: 'MISSING_ARGUMENT' }); const data = await ctx.api.get('/api/v1/quran/ayah', { surah, ayah }); return ctx.reply(`۞ ${data.surah} ${data.numberInSurah}\n${data.text}\n${data.translation || ''}`); } }),
  command({ name: 'quransearch', args: '<texto>', description: 'Busca texto en traducción del Corán.', category: 'quran', limit: true, execute: async (ctx) => { const data = await ctx.api.get('/api/v1/quran/search', { q: requireText(ctx) }); return ctx.reply(`۞ Resultados:\n${data.items.map((item) => `${item.surah}:${item.numberInSurah} — ${item.text}`).join('\n\n') || 'Sin resultados.'}`); } }),
  command({ name: 'randomayah', description: 'Obtiene una aleya aleatoria.', category: 'quran', limit: true, execute: async (ctx) => { const data = await ctx.api.get('/api/v1/quran/ayah', { surah: Math.floor(Math.random() * 114) + 1, ayah: 1 }); return ctx.reply(`۞ ${data.surah} ${data.numberInSurah}\n${data.text}\n${data.translation || ''}`); } })
];
