import { command } from '../_helpers.js';
import { changeRpg, inventoryFor, usePotion, claimQuest } from '../../database/economy.js';
import { randomInt } from '../../lib/utils.js';

const cooldownText = (until) => `⏳ Espera ${Math.ceil((until - Date.now()) / 60000)} minuto(s).`;
const levelFromXp = (xp) => Math.max(1, Math.floor(Math.sqrt(xp / 80)) + 1);

export default [
  command({ name: 'rpg', description: 'Muestra tu personaje RPG.', category: 'rpg', execute: (ctx) => ctx.reply(`⚔️ *${ctx.user.name}*\n❤️ Vida: ${ctx.user.rpg_health}/100\n⭐ Nivel: ${ctx.user.rpg_level}\n✨ XP RPG: ${ctx.user.rpg_xp}\n🗡️ Arma: ${ctx.user.rpg_weapon || 'ninguna'}`) }),
  command({ name: 'adventure', aliases: ['aventura'], description: 'Haz una aventura cada 15 minutos.', category: 'rpg', limit: true, execute: async (ctx) => { const result = await changeRpg(ctx.sender, (user) => { const next = Number(user.rpg_last_adventure) + 15 * 60_000; if (Date.now() < next) return { cooldown: next, fields: {} }; const damage = randomInt(5, 22); const gold = randomInt(35, 90) + (user.rpg_weapon === 'espada' ? 15 : 0); const xp = Number(user.rpg_xp) + 20; return { damage, gold, fields: { rpg_health: Math.max(1, Number(user.rpg_health) - damage), balance: Number(user.balance) + gold, rpg_xp: xp, rpg_level: levelFromXp(xp), rpg_last_adventure: Date.now() } }; }); if (result.cooldown) return ctx.reply(cooldownText(result.cooldown)); return ctx.reply(`🗺️ Aventura completada. Perdiste ${result.damage} vida y ganaste ${result.gold} monedas.`); } }),
  command({ name: 'hunt', aliases: ['cazar'], description: 'Caza cada 10 minutos.', category: 'rpg', limit: true, execute: async (ctx) => { const result = await changeRpg(ctx.sender, (user) => { const next = Number(user.rpg_last_hunt) + 10 * 60_000; if (Date.now() < next) return { cooldown: next, fields: {} }; const gold = randomInt(15, 55); const xp = Number(user.rpg_xp) + 10; return { gold, fields: { balance: Number(user.balance) + gold, rpg_xp: xp, rpg_level: levelFromXp(xp), rpg_last_hunt: Date.now() } }; }); if (result.cooldown) return ctx.reply(cooldownText(result.cooldown)); return ctx.reply(`🏹 Caza completada. Ganaste ${result.gold} monedas.`); } }),
  command({ name: 'fight', aliases: ['luchar'], description: 'Lucha contra un enemigo.', category: 'rpg', limit: true, execute: async (ctx) => { const result = await changeRpg(ctx.sender, (user) => { if (Number(user.rpg_health) < 10) return { weak: true, fields: {} }; const win = randomInt(0, 1) === 1; const damage = win ? randomInt(2, 10) : randomInt(15, 30); const reward = win ? randomInt(30, 75) : 0; return { win, damage, reward, fields: { rpg_health: Math.max(1, Number(user.rpg_health) - damage), balance: Number(user.balance) + reward } }; }); if (result.weak) return ctx.reply('❤️ Tu vida está baja. Usa .heal o compra una poción.'); return ctx.reply(result.win ? `⚔️ Ganaste el combate: +${result.reward} monedas, -${result.damage} vida.` : `💥 Perdiste el combate: -${result.damage} vida.`); } }),
  command({ name: 'equip', args: '<espada|escudo>', description: 'Equipa un objeto que poseas.', category: 'rpg', execute: async (ctx) => { const item = ctx.args[0]?.toLowerCase(); const items = await inventoryFor(ctx.sender); if (!item || !items.some((entry) => entry.item === item && entry.quantity > 0) || !['espada', 'escudo'].includes(item)) throw Object.assign(new Error('Debes poseer una espada o escudo.'), { code: 'ITEM_NOT_FOUND' }); await changeRpg(ctx.sender, (user) => ({ fields: { rpg_weapon: item } })); return ctx.reply(`🗡️ Equipaste: ${item}.`); } }),
  command({ name: 'heal', aliases: ['curar'], description: 'Restaura vida con una poción si tienes una.', category: 'rpg', execute: async (ctx) => { const result = await usePotion(ctx.sender); return ctx.reply(`❤️ Usaste una poción. Vida actual: ${result.health}/100.`); } }),
  command({ name: 'quest', aliases: ['mision'], description: 'Reclama la misión diaria tras aventura y caza.', category: 'rpg', execute: async (ctx) => { const result = await claimQuest(ctx.sender); if (result.claimed) return ctx.reply(`📜 Misión diaria completada: +${result.reward} monedas.`); return ctx.reply(result.reason === 'claimed' ? '📜 Ya reclamaste la misión de hoy.' : '📜 Completa una aventura y una caza hoy para reclamar 100 monedas.'); } })
];
