import { command, requireText } from '../_helpers.js';
import { getMentions, slug } from '../../lib/utils.js';
import { allUserJids, removePremium, setBan, setPremium } from '../../database/users.js';
import { blockCommand, blockedCommands, unblockCommand } from '../../database/commands.js';

const mentionedTarget = (ctx) => { const target = getMentions(ctx.message)[0]; if (!target) throw Object.assign(new Error('Menciona a un usuario.'), { code: 'MISSING_ARGUMENT' }); return target; };
export default [
  command({ name: 'owner', description: 'Muestra la información del owner.', category: 'owner', execute: (ctx) => ctx.reply('👑 Usa .ownerinfo para ver el propietario configurado.') }),
  command({ name: 'restart', description: 'Cierra el proceso para que un supervisor lo reinicie.', category: 'owner', owner: true, execute: async (ctx) => { await ctx.reply('🔄 Reinicio solicitado. El proceso se cerrará limpiamente.'); setTimeout(() => ctx.shutdown?.('restart'), 500); } }),
  command({ name: 'shutdown', description: 'Cierra bot y API limpiamente.', category: 'owner', owner: true, execute: async (ctx) => { await ctx.reply('🛑 Apagado solicitado.'); setTimeout(() => ctx.shutdown?.('shutdown'), 500); } }),
  command({ name: 'broadcast', args: '<mensaje>', description: 'Envía un mensaje a usuarios conocidos.', category: 'owner', owner: true, execute: async (ctx) => { const text = requireText(ctx); const recipients = await allUserJids(); let sent = 0; for (const jid of recipients) { try { await ctx.socket.sendMessage(jid, { text: `📣 *Anuncio*\n\n${text}` }); sent++; } catch { /* one recipient must not break the broadcast */ } } return ctx.reply(`📣 Broadcast completado: ${sent}/${recipients.length}.`); } }),
  command({ name: 'banuser', args: '<@usuario>', description: 'Bloquea el uso del bot a un usuario.', category: 'owner', owner: true, execute: async (ctx) => { await setBan(mentionedTarget(ctx), true); return ctx.reply('✅ Usuario bloqueado.'); } }),
  command({ name: 'unbanuser', args: '<@usuario>', description: 'Desbloquea un usuario.', category: 'owner', owner: true, execute: async (ctx) => { await setBan(mentionedTarget(ctx), false); return ctx.reply('✅ Usuario desbloqueado.'); } }),
  command({ name: 'addpremium', args: '<@usuario> <dias>', description: 'Activa Premium por días.', category: 'owner', owner: true, execute: async (ctx) => { const days = Number(ctx.args.at(-1)); if (!Number.isInteger(days) || days < 1 || days > 3650) throw Object.assign(new Error('Indica una cantidad de días válida.'), { code: 'MISSING_ARGUMENT' }); const user = await setPremium(mentionedTarget(ctx), days); return ctx.reply(`💎 Premium activado hasta ${new Date(user.premium_end).toLocaleDateString('es')}.`); } }),
  command({ name: 'delpremium', args: '<@usuario>', description: 'Retira Premium.', category: 'owner', owner: true, execute: async (ctx) => { await removePremium(mentionedTarget(ctx)); return ctx.reply('✅ Premium retirado.'); } }),
  command({ name: 'blockcmd', args: '<comando>', description: 'Bloquea globalmente un comando.', category: 'owner', owner: true, execute: async (ctx) => { const name = slug(ctx.args[0]); if (!ctx.registry.byName.has(name)) throw Object.assign(new Error('Comando no encontrado.'), { code: 'COMMAND_NOT_FOUND' }); await blockCommand(name); return ctx.reply(`🚫 ${ctx.prefix}${name} bloqueado.`); } }),
  command({ name: 'unblockcmd', args: '<comando>', description: 'Desbloquea un comando.', category: 'owner', owner: true, execute: async (ctx) => { const name = slug(ctx.args[0]); await unblockCommand(name); return ctx.reply(`✅ ${ctx.prefix}${name} desbloqueado.`); } }),
  command({ name: 'logs', description: 'Muestra diagnóstico del proceso y bloqueos.', category: 'owner', owner: true, execute: async (ctx) => { const blocks = await blockedCommands(); const memory = Math.round(process.memoryUsage().rss / 1024 / 1024); return ctx.reply(`📋 Diagnóstico\nRSS: ${memory} MB\nBloqueados: ${blocks.join(', ') || 'ninguno'}\nLos logs estructurados se escriben en stdout para no guardar contenido sensible.`); } })
];
